version: 2
project_name: post-upgrade-snapshot-generator
env:
  - CGO_ENABLED=1
builds:
  - id: post-upgrade-snapshot-generator-darwin-amd64
    main: ./cmd/main.go
    binary: post-upgrade-snapshot-generator
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/libwasmvmstatic_darwin.a -O /lib/libwasmvmstatic_darwin.a
    env:
      - CC=o64-clang
      - CGO_LDFLAGS=-L/lib
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.Name=post-upgrade-snapshot-generator
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.AppName=post-upgrade-snapshot-generator
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.Version=v{{ .Version }}
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.Commit={{ .Commit }}
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.BuildTags=netgo,ledger,static_wasm,pebbledb
      - -w -s
      - -linkmode=external
    tags:
      - netgo
      - ledger
      - static_wasm
      - pebbledb
  - id: post-upgrade-snapshot-generator-darwin-arm64
    main: ./cmd/main.go
    binary: post-upgrade-snapshot-generator
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/libwasmvmstatic_darwin.a -O /lib/libwasmvmstatic_darwin.a
    env:
      - CC=oa64-clang
      - CGO_LDFLAGS=-L/lib
    goos:
      - darwin
    goarch:
      - arm64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.Name=post-upgrade-snapshot-generator
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.AppName=post-upgrade-snapshot-generator
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.Version=v{{ .Version }}
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.Commit={{ .Commit }}
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.BuildTags=netgo,ledger,static_wasm,pebbledb
      - -w -s
      - -linkmode=external
    tags:
      - netgo
      - ledger
      - static_wasm
      - pebbledb
  - id: post-upgrade-snapshot-generator-linux-amd64
    main: ./cmd/main.go
    binary: post-upgrade-snapshot-generator
    hooks:
      pre:
        - wget -O /lib/libwasmvm_muslc.x86_64.a https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/libwasmvm_muslc.x86_64.a
        - echo "a4a3d09b36fabb65b119d5ba23442c23694401fcbee4451fe6b7e22e325a4bac /lib/libwasmvm_muslc.x86_64.a" | sha256sum -c
        - cp /lib/libwasmvm_muslc.x86_64.a /lib/libwasmvm_muslc.a
        - wget https://github.com/elys-network/resources/raw/refs/heads/main/x86_64-linux-musl-cross.tgz
        - tar xf x86_64-linux-musl-cross.tgz
        - mv x86_64-linux-musl-cross /opt/musl-cross
        - go clean -cache -modcache
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=/opt/musl-cross/bin/x86_64-linux-musl-gcc
      - LD=/opt/musl-cross/bin/x86_64-linux-musl-ld
      - CGO_LDFLAGS=-L/lib
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.Name=post-upgrade-snapshot-generator
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.AppName=post-upgrade-snapshot-generator
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.Version=v{{ .Version }}
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.Commit={{ .Commit }}
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.BuildTags=netgo,ledger,muslc,osusergo,pebbledb
      - -w -s
      - -linkmode=external
      - -extldflags '-Wl,-z,muldefs -static -lm'
    tags:
      - netgo
      - ledger
      - muslc
      - osusergo
      - pebbledb
  - id: post-upgrade-snapshot-generator-linux-arm64
    main: ./cmd/main.go
    binary: post-upgrade-snapshot-generator
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/libwasmvm_muslc.aarch64.a -O /usr/lib/libwasmvm_muslc.aarch64.a
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=aarch64-linux-gnu-gcc
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.Name=post-upgrade-snapshot-generator
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.AppName=post-upgrade-snapshot-generator
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.Version=v{{ .Version }}
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.Commit={{ .Commit }}
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.BuildTags=netgo,ledger,muslc,osusergo,pebbledb
      - -w -s
      - -linkmode=external
      - -extldflags '-lwasmvm_muslc.aarch64 -Wl,-z,muldefs -static -lm -ldl'
    tags:
      - netgo
      - ledger
      - muslc
      - osusergo
      - pebbledb
universal_binaries:
  - id: post-upgrade-snapshot-generator-darwin-universal
    ids:
      - post-upgrade-snapshot-generator-darwin-amd64
      - post-upgrade-snapshot-generator-darwin-arm64
    replace: false
archives:
  - id: zipped
    builds:
      - post-upgrade-snapshot-generator-darwin-universal
      - post-upgrade-snapshot-generator-linux-amd64
      - post-upgrade-snapshot-generator-linux-arm64
      - post-upgrade-snapshot-generator-darwin-amd64
      - post-upgrade-snapshot-generator-darwin-arm64
    name_template: "{{.ProjectName}}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
    files:
      - none*
  - id: binaries
    builds:
      - post-upgrade-snapshot-generator-darwin-universal
      - post-upgrade-snapshot-generator-linux-amd64
      - post-upgrade-snapshot-generator-linux-arm64
      - post-upgrade-snapshot-generator-darwin-amd64
      - post-upgrade-snapshot-generator-darwin-arm64
    name_template: "{{.ProjectName}}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: binary
    files:
      - none*
checksum:
  name_template: "sha256sum.txt"
  algorithm: sha256
changelog:
  disable: true
release:
  github:
    owner: elys-network
    name: post-upgrade-snapshot-generator
  replace_existing_draft: true
  header: |
    ## What's Changed

    See the full changelog [here](https://github.com/elys-network/post-upgrade-snapshot-generator/blob/v{{ .Version }}/CHANGELOG.md)
  name_template: "v{{.Version}}"
  mode: replace
  draft: false
