project_name: post-upgrade-snapshot-generator
env:
  - CGO_ENABLED=1
builds:
  - id: post-upgrade-snapshot-generator-darwin-amd64
    main: ./cmd/main.go
    binary: post-upgrade-snapshot-generator
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/libwasmvmstatic_darwin.a -O /lib/libwasmvmstatic_darwin.a
    env:
      - CC=o64-clang
      - CGO_LDFLAGS=-L/lib
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.Name=post-upgrade-snapshot-generator
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.AppName=post-upgrade-snapshot-generator
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.Version=v{{ .Version }}
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.Commit={{ .Commit }}
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.BuildTags=netgo,ledger,static_wasm,pebbledb
      - -w -s
      - -linkmode=external
    tags:
      - netgo
      - ledger
      - static_wasm
      - pebbledb
  - id: post-upgrade-snapshot-generator-darwin-arm64
    main: ./cmd/main.go
    binary: post-upgrade-snapshot-generator
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/libwasmvmstatic_darwin.a -O /lib/libwasmvmstatic_darwin.a
    env:
      - CC=oa64-clang
      - CGO_LDFLAGS=-L/lib
    goos:
      - darwin
    goarch:
      - arm64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.Name=post-upgrade-snapshot-generator
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.AppName=post-upgrade-snapshot-generator
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.Version=v{{ .Version }}
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.Commit={{ .Commit }}
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.BuildTags=netgo,ledger,static_wasm,pebbledb
      - -w -s
      - -linkmode=external
    tags:
      - netgo
      - ledger
      - static_wasm
      - pebbledb
  - id: post-upgrade-snapshot-generator-linux-amd64
    main: ./cmd/post-upgrade-snapshot-generator
    binary: post-upgrade-snapshot-generator
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/libwasmvm_muslc.x86_64.a -O /usr/lib/x86_64-linux-gnu/libwasmvm_muslc.a
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=x86_64-linux-gnu-gcc
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.Name=post-upgrade-snapshot-generator
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.AppName=post-upgrade-snapshot-generator
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.Version=v{{ .Version }}
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.Commit={{ .Commit }}
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.BuildTags=netgo,ledger,muslc,osusergo,pebbledb
      - -w -s
      - -linkmode=external
      - -extldflags '-Wl,-z,muldefs -static -lm'
    tags:
      - netgo
      - ledger
      - muslc
      - osusergo
      - pebbledb
  - id: post-upgrade-snapshot-generator-linux-arm64
    main: ./cmd/post-upgrade-snapshot-generator
    binary: post-upgrade-snapshot-generator
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/libwasmvm_muslc.aarch64.a -O /usr/lib/aarch64-linux-gnu/libwasmvm_muslc.a
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=aarch64-linux-gnu-gcc
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.Name=post-upgrade-snapshot-generator
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.AppName=post-upgrade-snapshot-generator
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.Version=v{{ .Version }}
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.Commit={{ .Commit }}
      - -X github.com/elys-network/post-upgrade-snapshot-generator/version.BuildTags=netgo,ledger,muslc,osusergo,pebbledb
      - -w -s
      - -linkmode=external
      - -extldflags '-Wl,-z,muldefs -static -lm'
    tags:
      - netgo
      - ledger
      - muslc
      - osusergo
      - pebbledb
universal_binaries:
  - id: post-upgrade-snapshot-generator-darwin-universal
    ids:
      - post-upgrade-snapshot-generator-darwin-amd64
      - post-upgrade-snapshot-generator-darwin-arm64
    replace: false
archives:
  - id: zipped
    builds:
      - post-upgrade-snapshot-generator-darwin-universal
      - post-upgrade-snapshot-generator-linux-amd64
      - post-upgrade-snapshot-generator-linux-arm64
      - post-upgrade-snapshot-generator-darwin-amd64
      - post-upgrade-snapshot-generator-darwin-arm64
    name_template: "{{.ProjectName}}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
    files:
      - none*
  - id: binaries
    builds:
      - post-upgrade-snapshot-generator-darwin-universal
      - post-upgrade-snapshot-generator-linux-amd64
      - post-upgrade-snapshot-generator-linux-arm64
      - post-upgrade-snapshot-generator-darwin-amd64
      - post-upgrade-snapshot-generator-darwin-arm64
    name_template: "{{.ProjectName}}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: binary
    files:
      - none*
checksum:
  name_template: "sha256sum.txt"
  algorithm: sha256
changelog:
  skip: true
release:
  github:
    owner: elys-network
    name: post-upgrade-snapshot-generator
  replace_existing_draft: true
  header: |
    ## What's Changed

    See the full changelog [here](https://github.com/elys-network/post-upgrade-snapshot-generator/blob/v{{ .Version }}/CHANGELOG.md)
  name_template: "v{{.Version}}"
  mode: replace
  draft: false
